version: 0.2

# env:
#   variables:
#     ANCHORE_CLI_URL: "http://anchore.example.com:8228/v1"
#     ANCHORE_CLI_USER: "admin"
#     ANCHORE_CLI_PASS: "foobar"
#     ANCHORE_CLI_SSL_VERIFY: "false"
#     ANCHORE_TIMEOUT: 300
#     ANCHORE_FAIL_ON_POLICY: "false"    
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # anchore-cli required for builds using standard AWS CodeBuild image
      - "pip3 install anchorecli"
      # awscli required for builds using engine-cli docker image 
      #- "pip3 install awscli"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "Adding image to Anchore engine at $ANCHORE_CLI_URL"
      - anchore-cli image add $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Waiting for analysis to complete"
      - anchore-cli image wait $IMAGE_REPO_NAME:$IMAGE_TAG --timeout $ANCHORE_TIMEOUT
      - echo "Analysis complete"
